export { Button, ButtonDelete } from './button/styled'
export { Text, TextBold } from './text/styled'
export { Title1 } from './title/styled'
export { Link } from './link/index'
export { Input } from './input/styled'
export { Label } from './label/styled'